# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clipwarp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import re
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QSize
from PyQt5.QtWidgets import (
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QStyle,
    QStyleOptionTab,
    QStylePainter,
    QTabBar,
    QTabWidget,
)


class TabBar(QTabBar):
    def tabSizeHint(self, index):
        s = QTabBar.tabSizeHint(self, index)
        s.transpose()
        return s

    def paintEvent(self, event):
        painter = QStylePainter(self)
        opt = QStyleOptionTab()

        for i in range(self.count()):
            self.initStyleOption(opt, i)
            painter.drawControl(QStyle.CE_TabBarTabShape, opt)
            painter.save()

            s = opt.rect.size()
            s.transpose()
            r = QtCore.QRect(QtCore.QPoint(), s)
            r.moveCenter(opt.rect.center())
            opt.rect = r

            c = self.tabRect(i).center()
            painter.translate(c)
            painter.rotate(90)
            painter.translate(-c)
            painter.drawControl(QStyle.CE_TabBarTabLabel, opt)
            painter.restore()


class VerticalTabWidget(QTabWidget):
    def __init__(self, *args, **kwargs):
        QTabWidget.__init__(self, *args, **kwargs)
        self.setTabBar(TabBar())
        self.setTabPosition(QtWidgets.QTabWidget.West)


class Ui_MainWindow(QObject):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ClipWarp")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(140, 0, 470, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 8, 331, 54))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Send = QtWidgets.QPushButton(self.frame_2)
        self.Send.setGeometry(QtCore.QRect(370, 38, 81, 24))
        self.Send.setObjectName("Send")
        self.Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Paste = QtWidgets.QPushButton(self.frame_2)
        self.Paste.setGeometry(QtCore.QRect(370, 8, 80, 24))
        self.Paste.setObjectName("Paste")
        self.Paste.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget = VerticalTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(2, 70, 608, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 25, 57, 24))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 25, 61, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def categorize_clips(self, clips):
        categorized = {"Text": []}
        for clip in clips:
            url_regex = re.compile(r"(https?://[^\s]+)")
            match = url_regex.search(clip["clips_text"])
            if match:
                url = match.group(0)
                domain = url.split("/")[2].replace("www.", "").replace(".com", "")
                if domain not in categorized:
                    categorized[domain] = []
                categorized[domain].append(clip)
            else:
                categorized["Text"].append(clip)
        return categorized

    def load_clips(self, clips):
        categorized_clips = self.categorize_clips(clips)
        self.render_tabs(categorized_clips)

    def render_tabs(self, categorized_clips):
        self.tabWidget.clear()
        for category, clips in categorized_clips.items():
            list_widget = QListWidget()
            reversed_clips = reversed(clips)
            for clip in reversed_clips:
                item = QListWidgetItem(clip["clips_text"])
                list_widget.addItem(item)
            self.tabWidget.addTab(list_widget, category)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClipWarp"))
        self.Send.setText(_translate("MainWindow", "Send"))
        self.Paste.setText(_translate("MainWindow", "Paste"))
        self.label.setText(_translate("MainWindow", "ClipWarp"))
        self.pushButton.setText(_translate("MainWindow", "Settings"))
